name: Maven test

# Lance le workflow lors
on:
  # d'un push sur la branche main
  push:
    branches: [ dev ]

  # permet de lancer ce workflow depuis l'onglet Actions
  workflow_dispatch:

# Tâches successives ou parallèles constituant le workflow
jobs:
  # Tâche unique appellée "build"
  build:
    # Système d'exploitation de lancement
    runs-on: ubuntu-latest

    # Séquence d'étapes à accompllir par la tâche
    steps:
      # Vérifie le dépôt depuis $GITHUB_WORKSPACE pour que la tâche puisse y accéder
      - uses: actions/checkout@v2
      
      # Mise à place du JDK 11
      - name: JDK 16
        uses: actions/setup-java@v2
        with:
          # JDK 11 distibué par Adopt
          distribution: adopt
          java-version: 16
      
      # Cache des dépendances Maven
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      # Test du projet avec Maven
      - run: mvn test
          

